spring:
  application.name: LeisureUp-BE
  threads.virtual.enabled: true

  profiles:
    default: local
    group:
      local:
        - common-secret
        - local-secret
      staging:
        - common-secret
        - staging-secret
      prod:
        - common-secret
        - prod-secret

  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379
      password:

logging:
  level:
    org.hibernate.SQL: debug
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ss.SSSz,Asia/Seoul
