name: CD prod blue/green

on:
  push:
    branches:
      - prod

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  # 0
  run-test-for-validation:
    uses: ./.github/workflows/run-test.yaml
    with:
      comment-test-result: false
    secrets:
      common-test-secret: ${{ secrets.COMMON_TEST_SECRET }}

  # 0
  inspect-color:
    uses: ./.github/workflows/inspect-color.yaml
    with:
      max_attempts: 30
      timeout: 5
    secrets:
      health-check-api: ${{ secrets.PROD_HEALTH_CHECK_API }}

  # 1
  push-image:
    needs:
      - run-test-for-validation
      - inspect-color
    uses: ./.github/workflows/push-docker-image.yaml
    with:
      tags: "${{ github.ref_name }}-${{ github.sha }}"
    secrets:
      docker-hub-id: ${{ secrets.DOCKER_HUB_ID }}
      docker-hub-pw: ${{ secrets.DOCKER_HUB_PW }}
      common-secret: ${{ secrets.COMMON_SECRET }}
      prod-secret: ${{ secrets.PROD_SECRET }}
      staging-secret: ${{ secrets.STAGING_SECRET }}

  # 1
  prepare-deploy:
    needs:
      - run-test-for-validation
      - inspect-color
    uses: ./.github/workflows/prepare-deploy.yaml
    with:
      compose-file-dir: "./"
      compose-file-name: "docker-compose.prod.blue-green.yaml"
    secrets:
      bastion-host-address: ${{ secrets.PROD_BASTION_ADDRESS }}
      bastion-host-id: ${{ secrets.PROD_BASTION_ID }}
      bastion-host-key: ${{ secrets.PROD_BASTION_KEY }}
      remote-host-address: ${{ secrets.PROD_APPLICATION_ADDRESS }}
      remote-host-id: ${{ secrets.PROD_APPLICATION_ID }}
      remote-host-key: ${{ secrets.PROD_APPLICATION_KEY }}

  # 2
  deploy:
    needs:
      - prepare-deploy
      - push-image
      - inspect-color
    uses: ./.github/workflows/deploy-blue-green.yaml
    with:
      image-tag: "${{ github.ref_name }}-${{ github.sha }}"
      rollback-dir: "./.rollback"
      rollback-name: "rollback-commands"
      compose-file-name: "docker-compose.prod.blue-green.yaml"
      to-blue: ${{ needs.inspect-color.outputs.type == 'GREEN' }}
      blue-name: "app-blue"
      green-name: "app-green"
      health-check-max-attempts: 60
      health-check-timeout: 5
    secrets:
      bastion-host-address: ${{ secrets.PROD_BASTION_ADDRESS }}
      bastion-host-id: ${{ secrets.PROD_BASTION_ID }}
      bastion-host-key: ${{ secrets.PROD_BASTION_KEY }}
      remote-host-address: ${{ secrets.PROD_APPLICATION_ADDRESS }}
      remote-host-id: ${{ secrets.PROD_APPLICATION_ID }}
      remote-host-key: ${{ secrets.PROD_APPLICATION_KEY }}
      docker-hub-id: ${{ secrets.DOCKER_HUB_ID }}
      docker-hub-pw: ${{ secrets.DOCKER_HUB_PW }}
      health-check-api: ${{ secrets.PROD_HEALTH_CHECK_API }}
      health-check-api-blue: ${{ secrets.PROD_HEALTH_CHECK_API_BLUE }}
      health-check-api-green: ${{ secrets.PROD_HEALTH_CHECK_API_GREEN }}

  # 3
  clean:
    needs:
      - deploy
      - inspect-color
    uses: ./.github/workflows/clean-blue-green.yaml
    with:
      compose-file-name: "docker-compose.prod.blue-green.yaml"
      prune-blue: ${{ needs.inspect-color.outputs.type == 'BLUE' }}
      blue-name: "app-blue"
      green-name: "app-green"
    secrets:
      bastion-host-address: ${{ secrets.PROD_BASTION_ADDRESS }}
      bastion-host-id: ${{ secrets.PROD_BASTION_ID }}
      bastion-host-key: ${{ secrets.PROD_BASTION_KEY }}
      remote-host-address: ${{ secrets.PROD_APPLICATION_ADDRESS }}
      remote-host-id: ${{ secrets.PROD_APPLICATION_ID }}
      remote-host-key: ${{ secrets.PROD_APPLICATION_KEY }}
