name: CI

# Required permission for test result comment
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  pull_request:
    branches:
      - develop
      - prod
      - staging

jobs:
  run-test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application
        uses: ./.github/workflows/composite/utils/build-application
        with:
          java_version: '21'

      - name: Run test
        continue-on-error: true
        id: test
        shell: bash
        run: |
          ./gradlew test --build-cache --parallel

      - name: Add test result as comment
        if: always()
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action@v2.19.0
        with:
          files: ./build/test-results/**/*.xml

      - name: Abort on test fail
        if: steps.test.outcome != true
        run: exit 1;
